# .goreleaser.yaml

version: 2

before:
  hooks:
    - go mod tidy
    # - go generate ./...

project_name: eevlark

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64   # enables arm64 for darwin (macOS Apple Silicon) + linux (arm64/RPi)
    ignore:
      - goos: windows
        goarch: arm64   # Exclude Windows arm64
    main: ./
    binary: eevlark

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}
      {{- end }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - src: scripts/*
      - src: README*
        dst: .
      - src: LICENSE*
        dst: .
      - src: "eevlark.yaml"
        dst: .
        strip_parent: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums.txt'
  algorithm: sha256

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "registry.gitlab.com/eevideo/eevlark:{{ .Tag }}"
      - "registry.gitlab.com/eevideo/eevlark:latest"
